Loading python3/3.11.7
  Loading requirement: intel-mkl/2023.2.0
Traceback (most recent call last):
  File "/home/563/hk7549/synthetic_model_test/test.py", line 263, in <module>
    false_alarm_task()
  File "/home/563/hk7549/synthetic_model_test/test.py", line 55, in false_alarm_task
    for result in p.map(false_alarm_rate_2, inputs):
                        ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'false_alarm_rate_2' where it is not associated with a value
